vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        feeds:
            uri_prefix: /uploads/
            upload_destination: '%kernel.project_dir%/public/uploads/feeds'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        user:
            uri_prefix: /uploads/
            upload_destination: '%kernel.project_dir%/public/uploads/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer